# Generated by Django 4.1.5 on 2023-01-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='member',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='member',
            name='joined_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
