# Generated by Django 4.1.5 on 2023-01-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_delete_question_remove_member_joined_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='joined_datetime',
        ),
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(null=True),
        ),
    ]
