# Generated by Django 4.1.5 on 2023-01-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_joined_datetime_member_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
